### ISSUE TITLE
Images aren't drawing

### ISSUE THREAD

**Issue by Mokuami** [kyranet/canvasConstructor#127]
None of the methods for drawing images are working for me, i'd provide stack trace if there was one. It just completely skips over the process or at least that's what it seems like

Example: `.addCircularImage(avatar, 20, 26, 64)`

**Comment by kyranet** [comment]
I need more context, what version of `canvas` and `canvas-constructor` are you using? What's the full code for this?

**Comment by Mokuami** [comment]
canvas: `^2.5.0`
canvas-constructor: `^3.0.1`,

```js
const fetched = await fetch(msg.member.user.displayAvatarURL());
if(!fetched.status !== 200) return this.client.utils.error('Failed To Get Avatar')
const targetAvatar = await result.buffer();
console.log(targetAvatar)
return new Canvas(400, 180)
.addCircularImage(targetAvatar, 20, 26, 64)
.toBufferAsync()
```i wish i could provide more but it just shows no signs of an error or a problem.

**Comment by kyranet** [comment]
Try this:

```diff
  const fetched = await fetch(msg.member.user.displayAvatarURL());
- if(!fetched.status !== 200) return this.client.utils.error('Failed To Get Avatar')
+ if (!fetched.ok) return this.client.utils.error('Failed To Get Avatar');
  const targetAvatar = await fetched.buffer();
  console.log(targetAvatar);
  return new Canvas(400, 180)
    .addCircularImage(targetAvatar, 20, 26, 64)
    .toBufferAsync()
```

And I think it doesn't work because displayAvatarURL will either give a webp, or a gif, both unsupported in Canvas, you need a jpg or a png:

```diff
- const fetched = await fetch(msg.member.user.displayAvatarURL());
+ const fetched = await fetch(msg.member.user.displayAvatarURL({ format: 'png' }));
```

With those changes, this should work.
![image](https://user-images.githubusercontent.com/24852502/57508843-fc356f80-7302-11e9-889c-e655768abe1d.png)

**Comment by Mokuami** [comment]
That did the trick, thank you very much!
