### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by Roki100** [kyranet/canvasConstructor#133]
any docs with list of things that can be done with this module?

**Comment by kyranet** [comment]
Many things! The only limit is your [imagination](https://onaircode.com/awesome-html5-canvas-examples-source-code/)!

**Comment by Roki100** [comment]
i dont understand that, thats something other 🤔

**Comment by kyranet** [comment]
There are over 50 methods in `canvas-constructor` (pretty much all non-experimental stuff that is available in Node.js, as well as the non-standard extras from `node-canvas`), while you can do good-looking things with only a few commands, it's only imagination and practise what define what can you do with canvas.

Just like Photoshop gives you around 20 tools, it's practise what makes the art, so I encourage you to practise and discover tricks that will allow you to do anything you like.

I would like to show everything that is possible to do with canvas, or with canvas-constructor, but just like there are thousands of years of art, it never stops evolving. There will always be somebody who will come from the nowhere and impress us with a new technique, and as this library gets updated, more methods will be supported, removing a lot of the limits, if there are any!

In the meanwhile, I **fully welcome** any contribution to docs or guides, showing everyone their techniques and skills with this library, I'll be more than happy to review them and see what the community makes!

You can, however, ask the community in our [official Discord server](https://discord.gg/taNgb9d) 😄

**Comment by Roki100** [comment]
so do i have chance to get list of all methods on discord server?

**Comment by kyranet** [comment]
They're all available in the [official website](https://canvasconstructor.js.org/#/docs/CanvasConstructor/master/class/Canvas)

**Comment by Roki100** [comment]
oh, thanks, i was searching for something like this :D

**Comment by kyranet** [comment]
I added the link to the official website to this repository, and a Discord widget (with the invite link) to the README, thanks you for reminding me!
