### ISSUE TITLE
Multiple Bevel or Round images mask away others

### ISSUE THREAD

**Issue by velddev** [kyranet/canvasConstructor#16]
Not sure if this is a bug here or in node-canvas, but I figured I'd post it here. I'm trying to add two bevelled images, but it only puts out one.

```
var canvas = new Canvas(512, 256, "png")
    .addBevelImage(background, 28, 28, 200, 200, 90)
    .addBevelImage(background, 284, 28, 200, 200, 90)
```

returns 

![image](https://user-images.githubusercontent.com/13852840/38174873-5f9683f6-35d4-11e8-82b1-6e3a5bfeac98.png)

**Comment by kyranet** [comment]
Have you tried with those two?

```javascript
var canvas = new Canvas(512, 256, "png")
	.save()
	.addBevelImage(background, 28, 28, 200, 200, 90)
	.restore()
	.addBevelImage(background, 284, 28, 200, 200, 90);
```

Or this one, which achieves the same thing:

```javascript
var canvas = new Canvas(512, 256, "png")
	.addImage(background, 28, 28, 200, 200, { radius: 90, type: 'bevel', restore: true })
	.addImage(background, 284, 28, 200, 200, { radius: 90, type: 'bevel', restore: true });
```

**Comment by YorkAARGH** [comment]
I'm going to go a head and close this as the author has not responded after a week.

**Comment by velddev** [comment]
Oh, my apologies. Some issues arose with work and school. I had a busy period, I'll report back soon again.
