### ISSUE TITLE
cannot add text in image

### ISSUE THREAD

**Issue by hansputera** [kyranet/canvasConstructor#336]
![Screenshot_2020-03-26-14-02-03-49](https://user-images.githubusercontent.com/47862061/77619245-66322400-6f6a-11ea-813c-61bc58b3adc1.png)

**Comment by namekinggamerboy** [comment]
I think use other TextFont

**Comment by kyranet** [comment]
Please edit the issue's description to include the code, I cannot read all of it as an image, and it's important for me to be able to read it fully.

**Comment by kyranet** [comment]
I will close this issue soon if no more information is given, I cannot help without being able to see the entire code and without having reproducible code.
