### ISSUE TITLE
<Canvas>.createCanvas(x, x) not new <canvas>

### ISSUE THREAD

**Issue by DasCalamity** [kyranet/canvasConstructor#9]
Canvas updated, and they changed new Canvas into Canvas.createCanvas()

**Comment by kyranet** [comment]
The current version of NPM is 1.6.7 and as far as I am aware, it uses `new Canvas()`. If you installed the development branch (2.0.0-alpha.6) from Github, then you may install the [2.0 branch](https://github.com/kyranet/canvasConstructor/tree/2.0).

```
$ npm install kyranet/canvasConstructor#2.0
```
